### ISSUE TITLE
Kubernetes NUVLA env variables are not visible to containers

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/job-engine#73]
## Docker

When you run docker-compose with this configuration, Compose looks for the  environment variable in the shell and substitutes its value in. 

If an environment variable is not set, Compose substitutes with an empty string. 
https://docs.docker.com/compose/compose-file/#variable-substitution

## Kubernetes
Kubernetes doesn't automatically do the substitution.

### Alternatives:
** 1) envsubst linux command**

Replace env variables in manifest by using envsubs before deploying to infrastructure
```
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: xyz
    env:
    - name: NUVLA_DEPLOYMENT_ID
       value: $NUVLA_DEPLOYMENT_ID
        ...
```
Inconvenient: can break deployment by replacing value that should not be substitute
**2) secret map that user have to extract values from manually**
Nuvla create a secret map that user can reference
```
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: xyz
    env:
    - name: NUVLA_DEPLOYMENT_ID
       valueFrom:
          secretKeyRef:
            name: nuvlasecret
            key: NUVLA_DEPLOYMENT_ID
        ...
Inconvenient: user should know the existence of this secret map from documentation
```

**Comment by cjdcordeiro** [comment]
I'd add a 3rd option
---
##### **3) do nothing **

do not support env var substitution for k8s. It's a valid argument. If they don't support, why should we? I see the value...but if it can cause more harm than good, then this is a valid choice as well

**Comment by schaubl** [comment]
@cjdcordeiro So how to pass parameters ?

**Comment by cjdcordeiro** [comment]
being said this, I'd either go for 3) or 1*)  :)

the 1*) is basically @0xbase12 's option 1) on steroids:
 - before deploying and before doing `envsubst`, parse the YAML file and extract just the `env` section. 
 - then use the `envsubst` just on that section, and put it back into the app manifest

**Comment by cjdcordeiro** [comment]
> @cjdcordeiro So how to pass parameters ?

you don't. If you were using k8s you wouldn't be allowed either.

With Helm however, it seems to be possible (never used)

**Comment by schaubl** [comment]
@cjdcordeiro Let's assume we have a surveillance application which needs to connect to an IP camera. How do we pass the URL of the camera's video stream when deploying the app ? We don't use K8s ?

**Comment by schaubl** [comment]
... or we use files as `config` and/or `secret`.

**Comment by 0xbase12** [comment]
I think I'll implement envsubst limited to replace variables from existing in env map only to limit the risk of breaking something in the manifest of the user.

**Comment by konstan** [comment]
For me it's first option, and on the whole manifest (which user would do on CLI anyways with `envsubst < deploy.yaml | kubectl create -f -`). Just need to add a context help on the fact that we do this. `NUVLA_` vars will highly likely be used only by sidecars. Other env vars as params will be used by main containers.

```
spec:
  containers:
  - name: nuvla-data-mounter
     image: nuvla-data-mounter
     env:
     - name: NUVLA_DEPLOYMENT_ID
        value: $NUVLA_DEPLOYMENT_ID
        ...
  - name: user-app
     image: user-image
     env:
     - name: USER_VAR
        value: $USER_VAR
```

`USER_VAR` can/must be set by user via Nuvla UI. 

Indeed, this becomes a non canonical treatment of k8s manifest. Or else we should disable `Environmental variables` section all together in the app definition when Kubernetes app subtype is selected.
