### ISSUE TITLE
[BUG] missing port mappings when ports are deployed in host mode

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/job-engine#77]
to replicate:
```
services:
 web:
  image: nginx
  ports:
   - target: 80
     protocol: "tcp"
     mode: "host"
```

then `docker service ls`
```
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
phvs7j47ahmy        test_web            replicated          1/1                 nginx:latest 
```

so we'll get no ports from the service, even though the nginx container has a published port on a certain node:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
907879eb328f        nginx:latest        "nginx -g 'daemon of…"   23 minutes ago      Up 23 minutes       0.0.0.0:32768->80/tcp ```

**Comment by 0xbase12** [comment]
As discussed with @cjdcordeiro. IMHO it's not a bug and it's not a bad design from Docker service.

Since the port is exposed at host level. This mean that the service is exposed only on the node which have the container running in it. 

So you can't reach the service port with using classic any node swarm ip + port to reach it. You have to go to the docker node ip + port.
You can only reach the service on the node where it's deployed.

This is why it's not visible directly in docker service.

To be discussed how to support that case.

**Comment by 0xbase12** [comment]
Consider this case:
```
version: "3.7"
services:
  nginx:
    image: nginx
    ports:
            - target: 80
              protocol: tcp
              mode: host
    deploy:
            replicas: 2
  nginx2:
    image: nginx
    ports:
            - target: 80
              protocol: tcp
```

We have the port exposed for service `nginx2`.
For `nginx` we have replicas 2 and port published at host level. 
When we list services we will get:
```
> $ docker stack services ng
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
pjs17u3puxm8        ng_nginx            replicated          2/2                 nginx:latest
xv5n9kctpva8        ng_nginx2           replicated          1/1                 nginx:latest        *:30003->80/tcp
```

And we list the tasks we will get:
```
> $ docker stack ps ng
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
tnbvi6ouy0rr        ng_nginx2.1         nginx:latest        docker-desktop      Running             Running 2 minutes ago
wqzrnua2oy87        ng_nginx.1          nginx:latest        docker-desktop      Running             Running 2 minutes ago                       *:32773->80/tcp
wjuockp9rgnv        ng_nginx.2          nginx:latest        docker-desktop      Running             Running 2 minutes ago                       *:32774->80/tcp
```

So here we have tasks names postfixed with numbers and multiple ports published. How we handle that case @cjdcordeiro ?
Create output parameter nginx.tcp.80 and we take a random value from repicas ?
Create output parameter nginx.1.tcp.80 and nginx.2.tcp.80 ?
What about the host ip. Since you can't access the service with any ip of the cluster but only with IP of the host where the service nginx.1 is running ? 
How the user should now where his task is running ?
